title: Game Dialog Script Language
description: A simple language for writing game dialogs with integrated logic
remote_theme: pages-themes/primer@v0.5.4

url: https://bitpatch.github.io
baseurl: /game-dialog

show_downloads: false

plugins:
  - jekyll-remote-theme
